name: UltimateStaff
version: @version@
api-version: 1.13
main: me.justplugins.ultimatestaff.Main
authors: [ Nathan, D1TZ ]
website: justplugins.xyz
description: "A advanced staff and punishment plugin made by Justplugins"